### ISSUE TITLE
Problem to decoding Visa Message

### ISSUE THREAD

**Issue by georgelanes** [shemistone/iso-8583-parser#1]
Hi, I'm work with financial cred card system (VISA, MASTER CARD, ELO and JCB).

I'm testing your code, but they have some problems to decoding Visa Message (0100) without header.

See the attached file (visa-message.txt). This file have the message.

The correct result is (my own code):
2:PAN:4593830056961514
3:Processing Code:000000
4:Amount, transaction:000000000800
6:Amount, cardholder billing:000000000800
7:Transmission date & time:0207113136
10:Conversion rate, cardholder billing:06150000
11:System trace audit number (STAN):002733
13:Local transaction date (MMDD):0207
14:Expiration date:3610
18:Merchant type, or merchant category code:5999
19:Acquiring institution (country code):0840
22:Point of service entry mode:0100
25:Point of service condition code:59
28:Amount, transaction fee: D00000000
32:Acquiring institution identification code:000000159150153
37:Retrieval reference number:903811002733
41:Card acceptor terminal identification:TERMID01
42:Card acceptor identification code:CARD ACCEPTOR  
43:Card acceptor name/location:MC DONALD                MIAME        US
49:Currency code, transaction:0840
51:Currency code, cardholder billing:0840
60:Aditional Pos Information:0900000007

[visa-message.txt](https://github.com/shemistone/iso-8583-parser/files/2999825/visa-message.txt)

**Comment by shemistone** [comment]
Hi, share the configuration file (iso_msg.xml) you are using?

**Comment by georgelanes** [comment]
Hi,

1. The xml (iso_visa.xml) config file have only the first five fields.
2. The file vip-system-base-i-tech-specs-volume-1.zip is the Visa spec.

[vip-system-base-i-tech-specs-volume-1.zip](https://github.com/shemistone/iso-8583-parser/files/3001050/vip-system-base-i-tech-specs-volume-1.zip)

[iso_visa.zip](https://github.com/shemistone/iso-8583-parser/files/3001046/iso_visa.zip)
